read_hdl -vhdl {attackpressed.vhd}
read_hdl -vhdl {VGA_char_animation_fsm.vhd}
read_hdl -vhdl {VGA_char_offset_adder.vhd}
read_hdl -vhdl {VGA_char_sprites.vhd}
read_hdl -vhdl {toplevel.vhd}
read_hdl -vhdl {coldet.vhd}
read_hdl -vhdl {collision_resolver.vhd}
read_hdl -vhdl {VGA_coloring.vhd}
read_hdl -vhdl {damagecalculator.vhd}
read_hdl -vhdl {VGA_dig3_num_splitter.vhd}
read_hdl -vhdl {VGA_frame_cnt.vhd}
read_hdl -vhdl {VGA_graphics_card.vhd}
read_hdl -vhdl {gravity.vhd}
read_hdl -vhdl {VGA_H_pix_cnt.vhd}
read_hdl -vhdl {h_player_movement.vhd}
read_hdl -vhdl {VGA_Hsync_gen.vhd}
read_hdl -vhdl {input_buffer.vhd}
read_hdl -vhdl {input_deserializer.vhd}
read_hdl -vhdl {input_driver.vhd}
read_hdl -vhdl {input_jump.vhd}
read_hdl -vhdl {input_register.vhd}
read_hdl -vhdl {input_toplevel.vhd}
read_hdl -vhdl {jump_calculator.vhd}
read_hdl -vhdl {killzonedetector.vhd}
read_hdl -vhdl {m_resethandler.vhd}
read_hdl -vhdl {m_toplevel.vhd}
read_hdl -vhdl {VGA_number_sprite.vhd}
read_hdl -vhdl {knockback_calculator.vhd}
read_hdl -vhdl {p_mux.vhd}
read_hdl -vhdl {physics_system.vhd}
read_hdl -vhdl {physics_top.vhd}
read_hdl -vhdl {position_adder.vhd}
read_hdl -vhdl {m_ram10bit.vhd}
read_hdl -vhdl {m_ram4bit.vhd}
read_hdl -vhdl {m_ram8bit.vhd}
read_hdl -vhdl {m_ram9bit.vhd}
read_hdl -vhdl {VGA_screen_scan.vhd}
read_hdl -vhdl {t_8bregs.vhd}
read_hdl -vhdl {toplevelattack.vhd}
read_hdl -vhdl {VGA_V_line_cnt.vhd}
read_hdl -vhdl {velocity_interpolator.vhd}
read_hdl -vhdl {VGA_Vsync_gen.vhd}
read_hdl -vhdl {m_writelogic.vhd}
read_hdl -vhdl {coldet-behaviour.vhd}
read_hdl -vhdl {VGA_frame_cnt_cfg.vhd}
read_hdl -vhdl {VGA_char_animation_fsm_cfg.vhd}
read_hdl -vhdl {jump_calculator_behaviour_cfg.vhd}
read_hdl -vhdl {collision_resolver_behaviour_cfg.vhd}
read_hdl -vhdl {position_adder_behaviour_cfg.vhd}
read_hdl -vhdl {gravity_behaviour_cfg.vhd}
read_hdl -vhdl {velocity_interpolator_behaviour_cfg.vhd}
read_hdl -vhdl {h_player_movement_behaviour_cfg.vhd}
read_hdl -vhdl {p_knockback_calculator_behaviour_cfg.vhd}
read_hdl -vhdl {VGA_char_sprites_cfg.vhd}
read_hdl -vhdl {VGA_number_sprite_cfg.vhd}
read_hdl -vhdl {VGA_dig3_num_splitter_cfg.vhd}
read_hdl -vhdl {VGA_char_offset_adder_cfg.vhd}
read_hdl -vhdl {VGA_H_pix_cnt_cfg.vhd}
read_hdl -vhdl {VGA_V_line_cnt_cfg.vhd}
read_hdl -vhdl {VGA_Hsync_gen_cfg.vhd}
read_hdl -vhdl {VGA_Vsync_gen_cfg.vhd}
read_hdl -vhdl {input_jump_behavioural_cfg.vhd}
read_hdl -vhdl {input_register_behavioural_cfg.vhd}
read_hdl -vhdl {input_deserializer_behavioural_cfg.vhd}
read_hdl -vhdl {input_buffer_behavioural_cfg.vhd}
read_hdl -vhdl {input_driver_behavioural_cfg.vhd}
read_hdl -vhdl {coldet-behaviour-cfg.vhd}
read_hdl -vhdl {killzonedetector-behavioural-cfg.vhd}
read_hdl -vhdl {damagecalculator-behavioural-cfg.vhd}
read_hdl -vhdl {attackpressed-behavioural-cfg.vhd}
read_hdl -vhdl {physics_system_behaviour_cfg.vhd}
read_hdl -vhdl {p_mux_behavioural_cfg.vhd}
read_hdl -vhdl {VGA_coloring_cfg.vhd}
read_hdl -vhdl {VGA_screen_scan_cfg.vhd}
read_hdl -vhdl {m_ram9bit_cfg.vhd}
read_hdl -vhdl {m_ram8bit_cfg.vhd}
read_hdl -vhdl {m_ram10bit_cfg.vhd}
read_hdl -vhdl {m_ram4bit_cfg.vhd}
read_hdl -vhdl {m_writelogic_cfg.vhd}
read_hdl -vhdl {m_resethandler_cfg.vhd}
read_hdl -vhdl {input_toplevel_structural_cfg.vhd}
read_hdl -vhdl {t_8bregs_rtl_cfg.vhd}
read_hdl -vhdl {toplevelattack-structural-cfg.vhd}
read_hdl -vhdl {physics_top_structural_cfg.vhd}
read_hdl -vhdl {graphics_card_structural_cfg.vhd}
read_hdl -vhdl {m_toplevel_cfg.vhd}
read_hdl -vhdl {chip_toplevel_structural_cfg.vhd}
