editPin -pin clk -layer 2 -fixedPin -assign {20.86 0} -side TOP
editPin -pin reset -layer 2 -fixedPin -assign {21.42 0} -side TOP
editPin -pin p1_controller -layer 2 -fixedPin -assign {21.98 0} -side TOP
editPin -pin p2_controller -layer 2 -fixedPin -assign {22.54 0} -side TOP
editPin -pin controller_latch -layer 2 -fixedPin -assign {29.82 0} -side TOP
editPin -pin controller_clk -layer 2 -fixedPin -assign {30.38 0} -side TOP
editPin -pin Vsync -layer 2 -fixedPin -assign {30.94 0} -side TOP
editPin -pin Hsync -layer 2 -fixedPin -assign {31.50 0} -side TOP
editPin -pin {R_data[3]} -layer 2 -fixedPin -assign {32.06 0} -side TOP
editPin -pin {R_data[2]} -layer 2 -fixedPin -assign {32.62 0} -side TOP
editPin -pin {R_data[1]} -layer 2 -fixedPin -assign {33.18 0} -side TOP
editPin -pin {R_data[0]} -layer 2 -fixedPin -assign {33.74 0} -side TOP
editPin -pin {G_data[3]} -layer 2 -fixedPin -assign {34.30 0} -side TOP
editPin -pin {G_data[2]} -layer 2 -fixedPin -assign {34.86 0} -side TOP
editPin -pin {G_data[1]} -layer 2 -fixedPin -assign {35.42 0} -side TOP
editPin -pin {G_data[0]} -layer 2 -fixedPin -assign {35.98 0} -side TOP
editPin -pin {B_data[3]} -layer 2 -fixedPin -assign {36.54 0} -side TOP
editPin -pin {B_data[2]} -layer 2 -fixedPin -assign {37.10 0} -side TOP
editPin -pin {B_data[1]} -layer 2 -fixedPin -assign {37.66 0} -side TOP
editPin -pin {B_data[0]} -layer 2 -fixedPin -assign {38.22 0} -side TOP
